"""
tests/test_real_training_data.py — W20-2 real-data ML training path.

Covers the 5 behaviours required by the W20-2 task spec:

  (1) ``MarketMLModel._load_real_training_data`` returns
      ``(None, None, None)`` when no real labeled samples are available
      (both ``fetch_training_samples`` and
      ``fetch_labeled_feature_vectors`` return empty).

  (2) ``MarketMLModel._load_real_training_data`` returns populated numpy
      arrays when real labeled samples are available (mocked
      ``fetch_training_samples`` returning ≥100 rows).

  (3) ``MarketMLModel.get_training_data`` falls back to the synthetic
      generator (3 000 rows) when no real data is available, and
      prefers real data when it is.

  (4) HTTP route ``GET /api/ml/training-data-status`` returns
      ``has_real_data=False`` when no real data is available, and
      ``has_real_data=True`` with correct class counts when real data
      exists (mocked).

  (5) ``MarketMLModel.fit_initial`` prefers real data — when ≥100 real
      labeled samples are available, ``training_source == "real_only"``
      and ``n_synthetic_samples == 0`` (no blend). When no real data is
      available, it falls back to synthetic-only training.

God Mode assessment context (W17-3, C1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The prior ``fit_initial`` blended 3 000 synthetic samples with real DB
samples when available. The synthetic labels are generated by a
hand-coded log-odds formula over the SAME feature columns the model is
trained on, so a model trained on the blend trivially "predicts" the
synthetic labels — structurally inflating Brier / AUC metrics. The W20-2
real-first policy eliminates that circularity: real data trains real,
synthetic is cold-start fallback only.

Mock strategy
~~~~~~~~~~~~~
  * ``mock_db`` — a ``MagicMock`` placed on ``core.timescale_db.timescale_db``
    via ``patch("core.timescale_db.timescale_db")``. The late import
    inside ``_load_real_training_data`` re-resolves the
    ``core.timescale_db.timescale_db`` attribute at call time, so the
    patch is picked up by the production code path. ``fetch_training_samples``
    and ``fetch_labeled_feature_vectors`` are configured per-test via
    ``mock_db.fetch_training_samples.return_value`` /
    ``mock_db.fetch_labeled_feature_vectors.return_value``.

  * ``_small_synth`` — patched ``ml.model._synthetic_training_data`` so
    a ``fit_initial`` call uses 100 rows (not the production 3 000) and
    keeps the per-test wall-time tractable (mirrors the ``fitted_model``
    fixture pattern in ``tests/test_ml_model.py``).

Sync ``def`` tests throughout — ``TestClient``'s sync portal manages the
FastAPI event loop for the HTTP route test (no ``pytestmark =
pytest.mark.asyncio`` needed, mirrors the convention in
``tests/test_feature_store.py`` / ``tests/test_ab_testing.py`` /
``tests/test_explainability.py``).
"""
from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pytest

# ── Bootstrap project root on sys.path (defensive; conftest.py also does this). ──
# Lets this file be run in isolation via
# ``python -m pytest tests/test_real_training_data.py`` — the project root
# is always importable as top-level modules (``ml.*``, ``core.*``) regardless
# of cwd.
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from ml.features import N_FEATURES  # noqa: E402  (sys.path must be set first)
from ml.model import (  # noqa: E402  (sys.path must be set first)
    MarketMLModel,
    _synthetic_training_data,
)


# =============================================================================
# Shared helpers
# =============================================================================

def _make_real_samples(n: int = 150, n_positive: int = 75) -> tuple[np.ndarray, np.ndarray]:
    """Build a controlled ``n``-row synthetic-but-realistic feature/label pair.

    The features are random uniform in ``[0, 1]`` per cell (so they're
    well-formed 38-dim vectors for ``scaler.fit_transform``), and the
    labels are a hand-crafted mix of 0s and 1s so the class-balance
    assertions in the HTTP route test are deterministic.

    Not the same as ``_synthetic_training_data`` (which generates labels
    via the log-odds formula) — these labels are arbitrary but
    deterministic, exercising ONLY the data-loading plumbing, not the
    model's fit quality.

    The labels are INTERLEAVED (shuffled) across the row axis so the
    time-ordered 80/20 split in ``fit_initial`` puts both classes in
    BOTH the train fold and the calibration fold. Without the shuffle,
    the first ``n_positive`` rows are all 1 and the rest are all 0 —
    so the train fold would be all-1 and the calibration fold all-0,
    which trips ``roc_auc_score``'s "need classifier with two classes"
    guard (the classifier was trained on a single-class target).
    """
    rng = np.random.RandomState(42)
    X = rng.uniform(0.0, 1.0, (n, N_FEATURES)).astype(np.float32)
    y = np.zeros(n, dtype=int)
    y[:n_positive] = 1
    # Interleave the labels so both classes appear in both folds of the
    # 80/20 time-ordered split (defensive against single-class folds).
    perm = rng.permutation(n)
    X = X[perm]
    y = y[perm]
    return X, y


def _small_synth(n: int = 100) -> tuple[np.ndarray, np.ndarray]:
    """100-row synthetic generator (mirrors the ``fitted_model`` fixture
    pattern in ``tests/test_ml_model.py``)."""
    return _synthetic_training_data(100)


# =============================================================================
# (1) _load_real_training_data returns (None, None, None) when no real data
# =============================================================================
class TestLoadRealTrainingDataNoData:
    """Verify the no-data fallback path of ``_load_real_training_data``."""

    def test_returns_none_tuple_when_db_empty(self):
        """When both ``fetch_training_samples`` and
        ``fetch_labeled_feature_vectors`` return empty results,
        ``_load_real_training_data`` must return
        ``(None, None, None)`` — the documented contract that lets the
        caller decide its own fallback (synthetic vs. abort)."""
        m = MarketMLModel()
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (None, [])
            mock_db.fetch_labeled_feature_vectors.return_value = []
            features, labels, timestamps = m._load_real_training_data()

        assert features is None, (
            f"features must be None when DB has no labeled samples, "
            f"got {type(features).__name__} (shape={getattr(features, 'shape', None)})"
        )
        assert labels is None, (
            f"labels must be None when DB has no labeled samples, "
            f"got {type(labels).__name__} (len={len(labels) if labels is not None else 'n/a'})"
        )
        assert timestamps is None, (
            f"timestamps must be None when DB has no labeled samples, "
            f"got {type(timestamps).__name__}"
        )

    def test_returns_none_when_fewer_than_100_samples(self):
        """When the DB returns rows but fewer than 100, the method
        returns ``(None, None, None)`` — the ≥100 threshold is the
        documented gate so a 5-row cold-start DB doesn't produce a
        degenerate model fit."""
        m = MarketMLModel()
        # 50 rows — below the 100-row threshold.
        X_few = np.zeros((50, N_FEATURES), dtype=np.float32)
        y_few = np.zeros(50, dtype=int)
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_few, y_few)
            # Fallback also returns too few rows.
            mock_db.fetch_labeled_feature_vectors.return_value = [
                (X_few[i], int(y_few[i])) for i in range(50)
            ]
            features, labels, timestamps = m._load_real_training_data()

        assert features is None, (
            "features must be None when DB has <100 labeled samples "
            f"(got {len(features) if features is not None else 'None'})"
        )
        assert labels is None
        assert timestamps is None

    def test_falls_back_to_fetch_labeled_feature_vectors(self):
        """When ``fetch_training_samples`` returns too few rows BUT
        ``fetch_labeled_feature_vectors`` returns ≥100 rows, the method
        uses the fallback source. This exercises the second branch of
        the real-data fetcher (used when only one outcome class is
        labeled so far, so the stratified query can't fill its quota)."""
        m = MarketMLModel()
        X_real, y_real = _make_real_samples(n=120, n_positive=60)
        # fetch_training_samples returns empty (stratified query failed).
        # fetch_labeled_feature_vectors returns 120 rows (unstratified).
        fallback_samples = [(X_real[i], int(y_real[i])) for i in range(120)]
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (None, [])
            mock_db.fetch_labeled_feature_vectors.return_value = fallback_samples
            features, labels, timestamps = m._load_real_training_data()

        assert features is not None, (
            "features must NOT be None when fetch_labeled_feature_vectors "
            "returns ≥100 rows (fallback path)"
        )
        assert labels is not None
        assert timestamps is not None
        assert len(features) == 120, (
            f"expected 120 fallback rows, got {len(features)}"
        )
        assert len(labels) == 120
        assert len(timestamps) == 120
        # Labels preserve the 60/60 split from the source.
        assert int(np.sum(labels)) == 60


# =============================================================================
# (2) _load_real_training_data returns arrays when real data available
# =============================================================================
class TestLoadRealTrainingDataWithData:
    """Verify the happy path of ``_load_real_training_data``."""

    def test_returns_arrays_when_fetch_training_samples_has_data(self):
        """When ``fetch_training_samples`` returns ≥100 rows, the
        method returns the arrays verbatim (after dtype coercion to
        ``float32`` / ``int``) and synthesizes a placeholder
        monotonic-decreasing timestamps array of equal length."""
        m = MarketMLModel()
        X_real, y_real = _make_real_samples(n=150, n_positive=75)
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_real, y_real)
            features, labels, timestamps = m._load_real_training_data()

        assert features is not None
        assert labels is not None
        assert timestamps is not None
        # Shape preserved (n_samples × N_FEATURES).
        assert features.shape == (150, N_FEATURES), (
            f"expected features.shape=(150, {N_FEATURES}), got {features.shape}"
        )
        # Labels preserve the 75-positive / 75-negative split.
        assert len(labels) == 150
        assert int(np.sum(labels)) == 75, (
            f"expected 75 positive labels, got {int(np.sum(labels))}"
        )
        # Timestamps are a 1-D array of length n_samples.
        assert timestamps.shape == (150,), (
            f"expected timestamps.shape=(150,), got {timestamps.shape}"
        )
        # Placeholder timestamps are monotonic decreasing (rows are
        # most-recent-first from the SQL ``ORDER BY timestamp DESC``).
        assert np.all(np.diff(timestamps) < 0), (
            f"timestamps must be monotonically decreasing (rows are "
            f"most-recent-first), got {timestamps[:5]}..."
        )

    def test_pads_short_feature_vectors(self):
        """When the DB returns feature rows with fewer than N_FEATURES
        columns (legacy schema), the method pads them with zeros so the
        downstream ``scaler.fit_transform`` doesn't fail. Mirrors the
        same pad/trim behaviour that was in the prior ``fit_initial``
        blend path."""
        m = MarketMLModel()
        # 150 rows × (N_FEATURES - 5) columns — simulates a legacy
        # schema with 5 missing feature columns.
        short_n = N_FEATURES - 5
        X_short = np.zeros((150, short_n), dtype=np.float32)
        X_short[:, 0] = 0.5  # mid_price
        y_short = np.zeros(150, dtype=int)
        y_short[:75] = 1
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_short, y_short)
            features, labels, timestamps = m._load_real_training_data()

        assert features is not None
        assert features.shape == (150, N_FEATURES), (
            f"padded features must have {N_FEATURES} columns, got {features.shape[1]}"
        )

    def test_trims_long_feature_vectors(self):
        """When the DB returns feature rows with MORE than N_FEATURES
        columns (forward-compat with a schema that added new columns
        before the model was retrained on them), the method trims to
        ``N_FEATURES``."""
        m = MarketMLModel()
        long_n = N_FEATURES + 3
        X_long = np.zeros((150, long_n), dtype=np.float32)
        X_long[:, 0] = 0.5
        y_long = np.zeros(150, dtype=int)
        y_long[:75] = 1
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_long, y_long)
            features, labels, timestamps = m._load_real_training_data()

        assert features is not None
        assert features.shape == (150, N_FEATURES), (
            f"trimmed features must have {N_FEATURES} columns, got {features.shape[1]}"
        )


# =============================================================================
# (3) get_training_data falls back to synthetic
# =============================================================================
class TestGetTrainingDataFallback:
    """Verify ``get_training_data`` prefers real, falls back to synthetic."""

    def test_returns_real_data_when_available(self):
        """When ``_load_real_training_data`` returns ≥100 rows,
        ``get_training_data`` returns them verbatim — no synthetic
        blend, no synthetic contamination of the labels."""
        m = MarketMLModel()
        X_real, y_real = _make_real_samples(n=200, n_positive=100)
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_real, y_real)
            features, labels, timestamps = m.get_training_data()

        # Real data path: 200 rows (not 3 000 — that would indicate the
        # synthetic fallback fired).
        assert features.shape == (200, N_FEATURES), (
            f"get_training_data should return real 200-row data, "
            f"got shape {features.shape} (likely synthetic fallback)"
        )
        assert len(labels) == 200
        assert int(np.sum(labels)) == 100

    def test_falls_back_to_synthetic_when_no_real_data(self):
        """When ``_load_real_training_data`` returns ``(None, None, None)``,
        ``get_training_data`` calls ``_synthetic_training_data(3000)`` and
        returns the synthetic arrays (with a placeholder timestamps
        array). This is the documented cold-start fallback path."""
        m = MarketMLModel()
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (None, [])
            mock_db.fetch_labeled_feature_vectors.return_value = []
            # Patch the synth generator to return 100 rows so the test
            # is fast (the production 3 000-row generator takes ~1s).
            with patch("ml.model._synthetic_training_data", _small_synth):
                features, labels, timestamps = m.get_training_data()

        # Synthetic fallback path: 100 rows (from the patched generator).
        assert features.shape == (100, N_FEATURES), (
            f"get_training_data synthetic fallback should return 100 rows, "
            f"got {features.shape}"
        )
        assert len(labels) == 100
        assert len(timestamps) == 100
        # Labels must be a 0/1 int array (synthetic generator output).
        assert set(np.unique(labels)).issubset({0, 1}), (
            f"synthetic labels must be 0/1, got unique values {np.unique(labels)}"
        )


# =============================================================================
# (4) HTTP route GET /api/ml/training-data-status
# =============================================================================
class TestTrainingDataStatusEndpoint:
    """Verify the ``GET /api/ml/training-data-status`` HTTP route."""

    @pytest.fixture
    def client(self):
        """Build a ``TestClient`` against a minimal FastAPI app with
        only the training-data-status route registered.

        Late-imports the production route handler from ``api.server``
        (which constructs the production FastAPI app at import time —
        the conftest env redirects make the heavy singleton init safe).
        We then add the SAME handler function on a fresh FastAPI app
        so the test isn't perturbed by the production app's middleware /
        dependency-injection graph.

        The handler closure captures ``ml_model`` from ``api.server``'s
        module scope, so it uses the same singleton the production
        route uses — monkey-patching ``ml_model._load_real_training_data``
        (or the underlying ``timescale_db`` singleton) is the lever the
        tests use to drive the route's branches.
        """
        from fastapi import FastAPI
        from fastapi.testclient import TestClient

        # Late import: triggers full ``api.server`` module load (the
        # conftest env redirects already point every *_DB_PATH env at
        # ``/tmp/pmbot_conftest_isolation``, so this is safe).
        from api.server import get_training_data_status

        fresh_app = FastAPI()
        fresh_app.add_api_route(
            "/api/ml/training-data-status",
            get_training_data_status,
            methods=["GET"],
        )
        return TestClient(fresh_app)

    def test_endpoint_returns_has_real_data_false_when_no_real_data(self, client):
        """When no real labeled samples are available, the endpoint
        returns ``has_real_data=False`` with zero counts. The route
        must NOT 500 — defensive try/except wraps the DB call."""
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (None, [])
            mock_db.fetch_labeled_feature_vectors.return_value = []
            resp = client.get("/api/ml/training-data-status")

        assert resp.status_code == 200, (
            f"expected 200, got {resp.status_code}: {resp.text}"
        )
        body = resp.json()
        assert body["has_real_data"] is False, (
            f"has_real_data must be False when no labeled samples, got {body['has_real_data']}"
        )
        assert body["n_samples"] == 0
        assert body["n_positive"] == 0
        assert body["n_negative"] == 0

    def test_endpoint_returns_has_real_data_true_when_data_available(self, client):
        """When ≥100 real labeled samples are available, the endpoint
        returns ``has_real_data=True`` with the correct sample count
        and class-balance breakdown."""
        X_real, y_real = _make_real_samples(n=150, n_positive=75)
        with patch("core.timescale_db.timescale_db") as mock_db:
            mock_db.fetch_training_samples.return_value = (X_real, y_real)
            resp = client.get("/api/ml/training-data-status")

        assert resp.status_code == 200, (
            f"expected 200, got {resp.status_code}: {resp.text}"
        )
        body = resp.json()
        assert body["has_real_data"] is True, (
            f"has_real_data must be True when ≥100 labeled samples available, "
            f"got {body['has_real_data']}"
        )
        assert body["n_samples"] == 150, (
            f"n_samples must be 150, got {body['n_samples']}"
        )
        assert body["n_positive"] == 75, (
            f"n_positive must be 75 (75 YES outcomes), got {body['n_positive']}"
        )
        assert body["n_negative"] == 75, (
            f"n_negative must be 75 (150 - 75 positive), got {body['n_negative']}"
        )

    def test_endpoint_reports_has_real_data_false_for_below_threshold(self, client):
        """When real labeled samples exist but fewer than 100,
        ``_load_real_training_data`` returns ``(None, None, None)``
        (per its threshold gate), so the endpoint returns
        ``has_real_data=False`` with zero counts — same shape as the
        no-data case. This is the documented W20-2 contract: the route
        can't tell apart "DB has 50 rows below threshold" from "DB is
        empty" because the underlying fetcher collapses both into
        ``(None, None, None)``. The operator inspects the DB directly
        (via ``GET /api/db/{table}``) for backfill progress."""
        X_few = np.zeros((50, N_FEATURES), dtype=np.float32)
        y_few = np.zeros(50, dtype=int)
        y_few[:25] = 1
        with patch("core.timescale_db.timescale_db") as mock_db:
            # fetch_training_samples returns 50 rows (below the 100
            # threshold), so the method falls through to the fallback.
            # fetch_labeled_feature_vectors returns [] (no fallback data)
            # so the method ultimately returns (None, None, None).
            mock_db.fetch_training_samples.return_value = (X_few, y_few)
            mock_db.fetch_labeled_feature_vectors.return_value = []
            resp = client.get("/api/ml/training-data-status")

        assert resp.status_code == 200
        body = resp.json()
        # Below the 100-row threshold → _load_real_training_data returns
        # (None, None, None), so the route surfaces zeros (mirrors the
        # no-data case — the threshold gate is inside the fetcher, not
        # the route).
        assert body["has_real_data"] is False, (
            f"has_real_data must be False below the 100-row threshold, "
            f"got {body['has_real_data']} (n_samples={body['n_samples']})"
        )
        assert body["n_samples"] == 0, (
            f"n_samples must be 0 when below threshold "
            f"(_load_real_training_data returns None), "
            f"got {body['n_samples']}"
        )
        assert body["n_positive"] == 0
        assert body["n_negative"] == 0


# =============================================================================
# (5) fit_initial prefers real data
# =============================================================================
class TestFitInitialPrefersRealData:
    """Verify ``fit_initial`` uses real-only training when ≥100 real
    labeled samples are available, and synthetic-only as cold-start
    fallback."""

    def test_fit_initial_trains_on_real_data_when_available(self):
        """When ≥100 real labeled samples are available, ``fit_initial``
        sets ``training_source == "real_only"``, ``n_real_samples >= 100``,
        and ``n_synthetic_samples == 0`` (no blend — the W20-2 contract)."""
        X_real, y_real = _make_real_samples(n=200, n_positive=100)
        with patch("core.timescale_db.timescale_db") as mock_db, \
             patch("ml.model._synthetic_training_data", _small_synth):
            mock_db.fetch_training_samples.return_value = (X_real, y_real)
            m = MarketMLModel()
            # Smaller estimator counts keep wall-time tractable.
            m.fit_initial(n_estimators_rf=10, n_estimators_gb=10)

        assert m.training_source == "real_only", (
            f"training_source must be 'real_only' when ≥100 real samples "
            f"are available, got {m.training_source!r}"
        )
        assert m.n_real_samples == 200, (
            f"n_real_samples must be 200 (count of real rows used), "
            f"got {m.n_real_samples}"
        )
        assert m.n_synthetic_samples == 0, (
            f"n_synthetic_samples must be 0 in the real-only branch "
            f"(no blend), got {m.n_synthetic_samples}"
        )
        # Belt-and-braces: model is fitted.
        assert m.is_fitted is True, (
            "is_fitted must be True after a successful fit_initial"
        )

    def test_fit_initial_falls_back_to_synthetic_when_no_real_data(self):
        """When no real labeled samples are available, ``fit_initial``
        falls back to synthetic-only training — sets
        ``training_source == "synthetic_only"``, ``n_real_samples == 0``,
        ``n_synthetic_samples > 0``. This is the cold-start fallback
        that keeps the predict path functional before the backfill loop
        has populated the SQLite store."""
        with patch("core.timescale_db.timescale_db") as mock_db, \
             patch("ml.model._synthetic_training_data", _small_synth):
            mock_db.fetch_training_samples.return_value = (None, [])
            mock_db.fetch_labeled_feature_vectors.return_value = []
            m = MarketMLModel()
            m.fit_initial(n_estimators_rf=10, n_estimators_gb=10)

        assert m.training_source == "synthetic_only", (
            f"training_source must be 'synthetic_only' when no real data, "
            f"got {m.training_source!r}"
        )
        assert m.n_real_samples == 0, (
            f"n_real_samples must be 0 in the synthetic-only branch, "
            f"got {m.n_real_samples}"
        )
        assert m.n_synthetic_samples > 0, (
            f"n_synthetic_samples must be > 0 in the synthetic-only branch, "
            f"got {m.n_synthetic_samples}"
        )
        assert m.is_fitted is True

    def test_fit_initial_real_only_does_not_blend_synthetic(self):
        """Critical correctness invariant: when real data is available,
        the synthetic generator is NOT called at all. This is the
        structural fix for the God Mode W17-3 C1 finding (synthetic
        labels contaminating the training set). Verified by spying on
        ``_synthetic_training_data`` and asserting it was never called
        in the real-data branch."""
        X_real, y_real = _make_real_samples(n=200, n_positive=100)
        # Use a side_effect that raises if called — proves the
        # synthetic generator was NOT invoked.
        def _synth_should_not_be_called(*args, **kwargs):
            raise AssertionError(
                "_synthetic_training_data must NOT be called when real "
                "labeled samples are available (W20-2 real-only contract)"
            )
        with patch("core.timescale_db.timescale_db") as mock_db, \
             patch("ml.model._synthetic_training_data", _synth_should_not_be_called):
            mock_db.fetch_training_samples.return_value = (X_real, y_real)
            m = MarketMLModel()
            # Must complete without the patched synth generator firing.
            m.fit_initial(n_estimators_rf=10, n_estimators_gb=10)

        assert m.training_source == "real_only"
        assert m.n_real_samples == 200
        assert m.n_synthetic_samples == 0
