"""
Consistency contract tests — verify an endpoint's response shape is
STABLE across multiple calls, pagination is respected, and the standard
response headers (``X-Request-ID``, ``X-API-Version``, ``X-RateLimit-Policy``)
are consistently emitted.

W15-3 — The frontend's React Query / polling hooks re-fetch every N
seconds; if the backend's response shape drifts between calls (e.g. a
field appears on the first call but is missing on the second because
of a conditional ``if`` branch in the handler), the Zod schema parse
flips between ``success`` and ``failure`` and the UI flickers between
data and ``—`` placeholders. These tests pin down shape stability.

Headers asserted:
  * ``X-Request-ID``  — UUID echoed on EVERY response (W12-6).
  * ``X-API-Version`` — version string echoed on EVERY response (W13-3).
  * ``X-RateLimit-Policy`` — informational policy header (W10-4).
  * ``X-Content-Type-Options: nosniff`` — OWASP A05 security header (W11-6).
"""
from __future__ import annotations

import pytest

# NOTE: no module-level ``pytestmark = pytest.mark.asyncio`` — every test in
# this module is synchronous (TestClient blocks on the request).


# ── Header constants ──────────────────────────────────────────────────────
HDR_REQUEST_ID = "X-Request-ID"
HDR_API_VERSION = "X-API-Version"
HDR_SUPPORTED_VERSIONS = "X-API-Supported-Versions"
HDR_RATE_LIMIT_POLICY = "X-RateLimit-Policy"
HDR_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"


def _content_type(resp) -> str:
    raw = resp.headers.get("content-type", "")
    return raw.split(";", 1)[0].strip().lower()


# ═══════════════════════════════════════════════════════════════════════════
# Response-header consistency
# ═══════════════════════════════════════════════════════════════════════════

class TestResponseHeadersConsistency:
    """Every response — 2xx, 4xx, 5xx — carries the same set of standard
    middleware-added headers. The frontend doesn't depend on them today
    (the React Query layer ignores response headers) but operators do
    (the X-Request-ID is the only way to self-service a log trace), so
    a regression here surfaces as "support can't trace my 500"."""

    @pytest.mark.parametrize("path", [
        "/api/health",
        "/api/status",
        "/api/positions",
        "/api/orders",
        "/api/trades",
    ])
    def test_x_request_id_present(self, client, auth_headers, path):
        """``X-Request-ID`` is on every response."""
        resp = client.get(path, headers=auth_headers)
        # Skip 502 (upstream Gamma failure on /api/markets) — those still
        # carry the header, but parametrize list above doesn't include
        # Gamma-dependent routes, so all should be 200.
        assert resp.headers.get(HDR_REQUEST_ID), (
            f"{HDR_REQUEST_ID} header missing on {path}"
        )

    @pytest.mark.parametrize("path", [
        "/api/health",
        "/api/status",
        "/api/positions",
    ])
    def test_x_request_id_is_unique_per_request(self, client, auth_headers, path):
        """Two calls to the same path must produce DIFFERENT request IDs
        (each is a fresh UUID generated by the request-logging middleware)."""
        r1 = client.get(path, headers=auth_headers)
        r2 = client.get(path, headers=auth_headers)
        id1 = r1.headers.get(HDR_REQUEST_ID)
        id2 = r2.headers.get(HDR_REQUEST_ID)
        assert id1 and id2
        assert id1 != id2, (
            f"{HDR_REQUEST_ID} should be unique per request; got {id1} twice"
        )

    @pytest.mark.parametrize("path", [
        "/api/health",
        "/api/status",
        "/api/positions",
    ])
    def test_x_api_version_present(self, client, auth_headers, path):
        """``X-API-Version`` is echoed on every response by the
        versioning middleware (W13-3)."""
        resp = client.get(path, headers=auth_headers)
        version = resp.headers.get(HDR_API_VERSION)
        assert version, f"{HDR_API_VERSION} header missing on {path}"
        # The default ACTIVE_VERSION is "v1"; we don't pin the exact
        # string so a future v2 bump doesn't break this test.
        assert version.startswith("v"), (
            f"{HDR_API_VERSION}={version!r} should start with 'v'"
        )

    def test_x_rate_limit_policy_present(self, client, auth_headers):
        """The rate-limit policy header is on every response (W10-4)."""
        resp = client.get("/api/health", headers=auth_headers)
        policy = resp.headers.get(HDR_RATE_LIMIT_POLICY)
        assert policy, f"{HDR_RATE_LIMIT_POLICY} header missing"
        # The policy string is "120/min read, 30/min write, 5/min heavy".
        assert "read" in policy.lower()

    def test_security_headers_present(self, client, auth_headers):
        """OWASP A05 security headers are on every response (W11-6)."""
        resp = client.get("/api/health", headers=auth_headers)
        assert resp.headers.get(HDR_CONTENT_TYPE_OPTIONS) == "nosniff"
        assert resp.headers.get("X-Frame-Options") == "DENY"


# ═══════════════════════════════════════════════════════════════════════════
# Shape stability — same endpoint, multiple calls
# ═══════════════════════════════════════════════════════════════════════════

class TestShapeStability:
    """The set of top-level keys returned by an endpoint must NOT change
    between calls. A handler that conditionally omits a key (e.g. ``if
    book: payload["mid"] = book.mid``) produces shape drift that breaks
    React Query's referential equality + the Zod schema's optional
    parsing on alternating polls."""

    def test_positions_keys_stable_across_calls(self, client, auth_headers):
        r1 = client.get("/api/positions", headers=auth_headers).json()
        r2 = client.get("/api/positions", headers=auth_headers).json()
        if isinstance(r1, dict) and isinstance(r2, dict):
            assert set(r1.keys()) == set(r2.keys()), (
                f"/api/positions top-level keys drift between calls: "
                f"{set(r1.keys()) ^ set(r2.keys())}"
            )

    def test_orders_keys_stable_across_calls(self, client, auth_headers):
        r1 = client.get("/api/orders", headers=auth_headers).json()
        r2 = client.get("/api/orders", headers=auth_headers).json()
        assert set(r1.keys()) == set(r2.keys()), (
            f"/api/orders top-level keys drift between calls: "
            f"{set(r1.keys()) ^ set(r2.keys())}"
        )

    def test_trades_keys_stable_across_calls(self, client, auth_headers):
        r1 = client.get("/api/trades", headers=auth_headers).json()
        r2 = client.get("/api/trades", headers=auth_headers).json()
        assert set(r1.keys()) == set(r2.keys()), (
            f"/api/trades top-level keys drift between calls: "
            f"{set(r1.keys()) ^ set(r2.keys())}"
        )

    def test_analytics_keys_stable_across_calls(self, client, auth_headers):
        """``/api/analytics`` is cached for 30s — but the SET of keys
        returned must be the same whether the cache hit or miss path
        was taken."""
        # First call populates the cache; second call hits the cache.
        r1 = client.get("/api/analytics", headers=auth_headers).json()
        r2 = client.get("/api/analytics", headers=auth_headers).json()
        assert set(r1.keys()) == set(r2.keys()), (
            f"/api/analytics top-level keys drift between cached and "
            f"uncached calls: {set(r1.keys()) ^ set(r2.keys())}"
        )

    def test_ml_metrics_keys_stable_across_calls(self, client, auth_headers):
        """``/api/ml/metrics`` is cached for 60s — same shape on hit and miss."""
        r1 = client.get("/api/ml/metrics", headers=auth_headers).json()
        r2 = client.get("/api/ml/metrics", headers=auth_headers).json()
        assert set(r1.keys()) == set(r2.keys()), (
            f"/api/ml/metrics top-level keys drift between cached and "
            f"uncached calls: {set(r1.keys()) ^ set(r2.keys())}"
        )


# ═══════════════════════════════════════════════════════════════════════════
# Pagination — limit / offset params are respected
# ═══════════════════════════════════════════════════════════════════════════

class TestPaginationContract:
    """``limit`` query params must cap the result list length and the
    count must reflect the actual returned slice, not the underlying total.
    """

    def test_trades_limit_caps_list_length(self, client, auth_headers):
        """``GET /api/trades?limit=10`` must return ≤ 10 trades."""
        resp = client.get("/api/trades?limit=10", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.json()
        assert len(data["trades"]) <= 10
        # count is the slice length, not the underlying total.
        assert data["count"] == len(data["trades"])

    def test_trades_smaller_limit_returns_fewer_or_equal(self, client, auth_headers):
        """``limit=3`` must return ≤ ``limit=10``'s trade count."""
        small = client.get("/api/trades?limit=3", headers=auth_headers).json()
        large = client.get("/api/trades?limit=10", headers=auth_headers).json()
        assert small["count"] <= large["count"]

    def test_events_limit_caps_list_length(self, client, auth_headers):
        """``GET /api/events?n=5`` must return ≤ 5 events."""
        resp = client.get("/api/events?n=5", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.json()
        events = data.get("events", data if isinstance(data, list) else [])
        assert len(events) <= 5

    def test_audit_logs_limit_caps_list_length(self, client, auth_headers):
        """``GET /api/audit/logs?limit=5`` must return ≤ 5 log rows."""
        resp = client.get("/api/audit/logs?limit=5", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.json()
        # Audit log endpoint returns ``{logs: [...], count: int}``.
        if isinstance(data, dict) and "logs" in data:
            assert len(data["logs"]) <= 5

    def test_decisions_rejected_limit_caps_list_length(self, client, auth_headers):
        """``GET /api/decisions/rejected?limit=5`` must return ≤ 5 rejections."""
        resp = client.get(
            "/api/decisions/rejected?limit=5", headers=auth_headers
        )
        assert resp.status_code == 200
        data = resp.json()
        if isinstance(data, dict) and "rejections" in data:
            assert len(data["rejections"]) <= 5


# ═══════════════════════════════════════════════════════════════════════════
# Content-Type consistency
# ═══════════════════════════════════════════════════════════════════════════

class TestContentTypeConsistency:
    """Every JSON route must return ``Content-Type: application/json``
    (with optional ``; charset=utf-8`` suffix). A regression to
    ``text/plain`` would silently break the frontend's ``res.json()`` parse
    on some browsers (the WHATWG fetch spec is permissive, but a few older
    Safari versions still gate JSON parsing on the content-type header)."""

    @pytest.mark.parametrize("path", [
        "/api/health",
        "/api/status",
        "/api/positions",
        "/api/orders",
        "/api/trades",
        "/api/events",
        "/api/cache/stats",
        "/api/rate-limit/stats",
        "/api/observability",
        "/api/attribution",
    ])
    def test_content_type_is_application_json(self, client, auth_headers, path):
        resp = client.get(path, headers=auth_headers)
        assert resp.status_code == 200
        assert _content_type(resp) == "application/json", (
            f"{path} returned content-type "
            f"{resp.headers.get('content-type')!r}"
        )
